/**
 * BulkPayrollImport — CSV bulk import for `usePayStreamV2.createStream`.
 *
 * Expected CSV columns: `name,address,amount_per_cycle,period_seconds,duration_cycles[,jitter_seconds]`
 *
 * For every valid row: create a stream targeted at `address` (encrypted hint
 * is generated by the hook), with `endTime = startTime + period * duration`.
 * Each successful create writes a receipt and shows green; failures show red
 * with the error message inline.
 */
import { useState } from "react";
import { isAddress } from "viem";
import { Card } from "@/components/elite/Layout";
import { Button } from "@/components/ui/button";
import { Loader2, Upload, AlertTriangle, CheckCircle2 } from "lucide-react";
import { usePayStreamV2 } from "@/hooks/usePayStreamV2";
import { useReceipts } from "@/hooks/useReceipts";
import { arbitrumSepolia } from "viem/chains";

interface ParsedRow {
  name: string;
  address: `0x${string}`;
  amountPerCycle: string;
  periodSeconds: number;
  durationCycles: number;
  jitterSeconds: number;
  invalid?: string;
}

interface ResultRow extends ParsedRow {
  status: "pending" | "ok" | "error";
  txHash?: `0x${string}`;
  streamId?: bigint;
  error?: string;
}

function parseCSV(text: string): ParsedRow[] {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  // Skip a header row if it looks like one.
  const start = /^name|^address/i.test(lines[0] ?? "") ? 1 : 0;
  const rows: ParsedRow[] = [];
  for (let i = start; i < lines.length; i++) {
    const cols = lines[i].split(",").map((c) => c.trim());
    if (cols.length < 5) {
      rows.push({
        name: cols[0] ?? `row-${i}`,
        address: "0x0" as `0x${string}`,
        amountPerCycle: "0",
        periodSeconds: 0,
        durationCycles: 0,
        jitterSeconds: 0,
        invalid: `Too few columns (${cols.length})`,
      });
      continue;
    }
    const [name, address, amountPerCycle, periodSeconds, durationCycles, jitterSeconds] = cols;
    let invalid: string | undefined;
    if (!isAddress(address)) invalid = "Invalid address";
    const period = Number(periodSeconds);
    const duration = Number(durationCycles);
    const jitter = Number(jitterSeconds ?? "0");
    const amount = parseFloat(amountPerCycle);
    if (!invalid && (!Number.isFinite(period) || period < 60)) invalid = "period_seconds must be ≥ 60";
    if (!invalid && (!Number.isFinite(duration) || duration < 1)) invalid = "duration_cycles must be ≥ 1";
    if (!invalid && (!Number.isFinite(amount) || amount <= 0)) invalid = "amount_per_cycle must be > 0";

    rows.push({
      name,
      address: address as `0x${string}`,
      amountPerCycle,
      periodSeconds: period,
      durationCycles: duration,
      jitterSeconds: Number.isFinite(jitter) ? jitter : 0,
      invalid,
    });
  }
  return rows;
}

export default function BulkPayrollImport() {
  const stream = usePayStreamV2();
  const receipts = useReceipts();
  const [rows, setRows] = useState<ResultRow[]>([]);
  const [busy, setBusy] = useState(false);
  const [globalError, setGlobalError] = useState<string | null>(null);

  const onFile = async (file: File) => {
    setGlobalError(null);
    try {
      const text = await file.text();
      const parsed = parseCSV(text);
      setRows(parsed.map((r) => ({ ...r, status: r.invalid ? "error" : "pending", error: r.invalid })));
    } catch (e) {
      setGlobalError((e as Error).message);
    }
  };

  const runAll = async () => {
    setBusy(true);
    const next = [...rows];
    for (let i = 0; i < next.length; i++) {
      const r = next[i];
      if (r.status === "error") continue;
      try {
        const startTime = Math.floor(Date.now() / 1000);
        const endTime = startTime + r.periodSeconds * r.durationCycles;
        const { hash, streamId } = await stream.createStream({
          recipientAddress: r.address,
          periodSeconds: r.periodSeconds,
          startTime,
          endTime,
          jitterSeconds: r.jitterSeconds,
        });
        next[i] = { ...r, status: "ok", txHash: hash, streamId };
        receipts.add({
          kind: "stream-create",
          txHash: hash,
          chainId: arbitrumSepolia.id,
          amount: r.amountPerCycle,
          recipientLabel: r.name,
          meta: { streamId: streamId.toString(), periodSeconds: r.periodSeconds, durationCycles: r.durationCycles },
        });
        setRows([...next]);
      } catch (e) {
        next[i] = { ...r, status: "error", error: (e as Error).message };
        setRows([...next]);
      }
    }
    setBusy(false);
  };

  const validCount = rows.filter((r) => r.status !== "error" || r.status === "pending").length;

  return (
    <Card className="p-6">
      <h3 className="font-display text-lg text-foreground mb-1">Bulk payroll import</h3>
      <p className="text-[12px] text-muted-foreground/70 mb-4 leading-relaxed">
        Upload CSV with columns: <code className="text-emerald-300 font-mono">name,address,amount_per_cycle,period_seconds,duration_cycles[,jitter_seconds]</code>.
        Each valid row produces one privacy-hardened V2 stream.
      </p>
      <label className="flex items-center gap-2 cursor-pointer text-[12px] text-emerald-300 hover:text-emerald-200 mb-4">
        <Upload className="w-3.5 h-3.5" />
        <span>Choose CSV file</span>
        <input
          type="file"
          accept=".csv,text/csv"
          onChange={(e) => e.target.files?.[0] && void onFile(e.target.files[0])}
          className="hidden"
        />
      </label>
      {globalError && (
        <div className="mb-3 text-[12px] text-red-300">{globalError}</div>
      )}

      {rows.length > 0 && (
        <>
          <div className="rounded-md border border-white/10 overflow-hidden mb-4 max-h-64 overflow-y-auto">
            <table className="w-full text-[11px] font-mono">
              <thead className="bg-white/[0.04] text-muted-foreground/70 sticky top-0">
                <tr>
                  <th className="text-left px-2 py-1.5">#</th>
                  <th className="text-left px-2 py-1.5">Name</th>
                  <th className="text-left px-2 py-1.5">Address</th>
                  <th className="text-right px-2 py-1.5">Amt</th>
                  <th className="text-right px-2 py-1.5">Period</th>
                  <th className="text-right px-2 py-1.5">×</th>
                  <th className="text-left px-2 py-1.5">Status</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r, i) => {
                  const tone =
                    r.status === "ok"
                      ? "text-emerald-300"
                      : r.status === "error"
                        ? "text-red-300"
                        : "text-foreground/85";
                  return (
                    <tr key={i} className={`border-t border-white/[0.04] ${tone}`}>
                      <td className="px-2 py-1.5">{i + 1}</td>
                      <td className="px-2 py-1.5">{r.name}</td>
                      <td className="px-2 py-1.5">
                        {r.address.slice(0, 6)}…{r.address.slice(-4)}
                      </td>
                      <td className="px-2 py-1.5 text-right">{r.amountPerCycle}</td>
                      <td className="px-2 py-1.5 text-right">{r.periodSeconds}s</td>
                      <td className="px-2 py-1.5 text-right">{r.durationCycles}</td>
                      <td className="px-2 py-1.5">
                        {r.status === "ok" && (
                          <span className="inline-flex items-center gap-1">
                            <CheckCircle2 className="w-3 h-3" /> #{r.streamId?.toString()}
                          </span>
                        )}
                        {r.status === "error" && (
                          <span className="inline-flex items-center gap-1" title={r.error}>
                            <AlertTriangle className="w-3 h-3" /> {r.error?.slice(0, 32)}
                          </span>
                        )}
                        {r.status === "pending" && "ready"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <Button onClick={() => void runAll()} disabled={busy || validCount === 0}>
            {busy ? (
              <>
                <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" /> Creating streams…
              </>
            ) : (
              <>Create {rows.filter((r) => r.status === "pending").length} streams</>
            )}
          </Button>
        </>
      )}
    </Card>
  );
}
